### PR TITLE
Fix #106 index out of range in WasmState.getLocals

### LINKED ISSUE #106: Exception in `WasmState.getLocals`
The following index can be out of range:

https://github.com/TOPLLab/WARDuino-VSCode/blob/be8fe97a6f112a9b69be998f4662b87c1bece33a/src/State/AllState.ts#L157

@carllocos Why is there a plus one?

---

**More information on the bug:**

fp: 0
stack: 5 items

dump:
```json
{"pc":4172,"breakpoints":[4687],"callstack":[{"type":0,"fidx":"0x25","sp":-1,"fp":-1,"idx":0,"block_key":0,"ra":5917},{"type":0,"fidx":"0x1f","sp":-1,"fp":0,"idx":1,"block_key":0,"ra":5082},{"type":0,"fidx":"0x1e","sp":-1,"fp":0,"idx":2,"block_key":0,"ra":4317}],"globals":[{"idx":0,"type":"i32","value":1648},{"idx":1,"type":"i32","value":3248},{"idx":2,"type":"i32","value":3280},{"idx":3,"type":"i32","value":3312},{"idx":4,"type":"i32","value":3344},{"idx":5,"type":"i32","value":3376},{"idx":6,"type":"i32","value":3472},{"idx":7,"type":"i32","value":1},{"idx":8,"type":"i32","value":3248},{"idx":9,"type":"i32","value":0},{"idx":10,"type":"i32","value":1},{"idx":11,"type":"i32","value":1568}],"stack":[{"idx":0,"type":"i32","value":0},{"idx":1,"type":"i32","value":0},{"idx":2,"type":"i32","value":0},{"idx":3,"type":"i32","value":0},{"idx":4,"type":"i32","value":0}],"events": []}
```

WAT code:

```wasm
 (func $game/initSnake
  (local $0 i32)
  (local $1 i32)
  (local $2 i32)
  (local $3 i32)
  (local $4 i32)
  ;;@ game.ts:38:1
  (global.set $game/s_length
   ;;@ game.ts:38:12
   (i32.const 1)  ;; <---------------------------- pc
  )
  (local.set $0
   (global.get $game/snake)
  )
  (i32.store
   (local.tee $1
    (call $game/Coordinate#constructor)
   )
  ;; ...
```

Instruction 4172 is the `(i32.const 1)`.

---

image

### PR DESCRIPTION
**Pull request by tolauwae**

### CODE REVIEW

**Comment by tolauwae** [comment]
**Some context** 

Now the index can be `-1`, so we get another out of range index. 

Looking further into the problem, I have the following thought: the plugin tries to get the locals directly from the stack. This has a couple of disadvantages:

- This is apparently not very easy, since there are a lot of edge cases where it doesn't work. Specifically:
    - on the `main` branch: can't parse dump on first instruction of function. This means you always have to step twice to enter a function, and breakpoints don't work on the first line of a function.
    - after the fix on this branch: doesn't work at start of main when the `frame pointer` is `-1`
- This means the plugin is reimplementing logic from the virtual machine.

I suspect the idea here was, since the stack is included in the dump anyway for the stack view, the plugin can keep the dump smaller by not requesting the locals.

**Proposal**

The refactored plugin tries to get locals from the stack.

However, I believe the locals are not always on the stack. At the start of a function the locals are on the stack, but they can be consumed by functions and wasm instructions. So it is actually impossible to get in locals from the stack.

It think we need to return to dumping locals directly.

@chscholl @carllocos @elisagb is my thinking right on this?

**Comment by tolauwae** [comment]
Unfortunately I can't implement this, because I don't understand the `inspect` command. @carllocos do you have documentation of the specification of the arguments for this new command?

**Comment by tolauwae** [comment]
The buggy behaviour seems to be fixed now for the demo. But there is still an issue, which may possibly be on the vm side.

Getting locals in the plugin from the stack had a hardcoded +1. This caused a index out-of-range exception that causes the plugin not to update and breakpoints to not work.

Getting the locals from the stack rather than directly from the debugger dump, means we are reimplementing vm logic.
So this comes down doing the same as as `i_instr_get_local`, which does not include the +1.

https://github.com/TOPLLab/WARDuino/blob/006128f8ba027b54f55d0354b1e4cc0fbb6b915e/src/Interpreter/instructions.cpp#L516-L524

Therefore I think the code right now is correct.

Unfortunately, now the index can be `-1`, so we get another out of range index. I fixed this by simply returning NaN.
However, how can there be locals if the index is `-1`?

This seems impossible. I would expect that a -1 means there are no locals.
So is the dump wrong? Is the vm wrong?

@carllocos Is my thing right on this? any idea what is going on?

**Comment by carllocos** [comment]
> Getting the locals from the stack rather than directly from the debugger dump, means we are reimplementing vm logic.
So this comes down doing the same as as i_instr_get_local, which does not include the +1.

I realise indeed that there is already an implementation to retrieve the locals but the reason why I refrained myself from using it is because we can derive the locals from the stack. If we would have to request the locals via a separate interrupt it would require additional message interchange which in future work may be something that we want to limit (e.g., due to network delays). Also if my understanding is correct of the implementation of the local interrupt, the locals interrupt only gives us information of the locals for the current function. This is a problem when trying to view the locals of a function lower in the callstack. So trying to derive the locals from the stack is in my opinion a more general approach which has the additional benefit to reduce network communication. 

> @carllocos Is my thinking right on this? any idea what is going on?

Unfortunately removing the `+1` does not really fix the issue since the problem stems from using the `fp` as a way to derive the locals from the stack. The reason on why using the `fp` is an issue is better explained in comment https://github.com/TOPLLab/WARDuino-VSCode/issues/106#issuecomment-1602813219

If fine by you, I propose to take over this PR. I will fix this issue.

**Comment by chscholl** [comment]
I thought that the whole  point of the changes to the VM were that we can now ask very detailed information instead of getting a whole dump? This seems to be the same kind of thing instead of having to retrieve the whole stack we can just ask the VM to give us the locals. In any case it would be worthwhile to have both, i.e. that we can simply ask the VM for locals and that we can get the whole stack when needed.

**Comment by tolauwae** [comment]
Yes that makes more sense. Also the stack view will probably be hidden whenever you are debugging Typescript or Rust, so you don't need that info for that view either. Only for locals of functions lower in the callstack, which can be requested when necessary.

**Comment by tolauwae** [comment]
However, for those locals of other functions. We still need this code to work. So I think we should fix that in this PR. And have a separate PR that refactors the code to request the locals directly.

**Comment by carllocos** [comment]
Indeed we could have both: the whole stack or only the locals of any function in the callstack. However, if we would only request the locals and no longer the full stack we would lose the view on the arguments provided to a function call. Therefore I believe that in the separate PR, as Tom suggests, we should also make it possible to request both kinds of values: the locals and arguments per function in the callstack.

**Comment by tolauwae** [comment]
Wouldn't it make more sense that when you request the locals of the current function you also get the arguments? After all in the wasm spec, there is no difference between the two.

I see no real need to request locals from functions other than the current one. They can't update anyway, so we don't need to update them.

But specifically for this PR. What still needs to be done so we can merge the fix for the index out of range?

**Comment by carllocos** [comment]
Yes agree, we should be able to request both locals and arguments. And this as a single request.

To be precise, I'm talking about giving access to the locals and arguments of only the functions parts of the callstack. So not any function. The users could see the locals and arguments of the other functions in the callstack by clicking on any item in the call stack view of the plugin. By default the plugin would only show the locals and arguments of the current function but through clicks, the users could choose to see the locals and args of other function not yet completed. And for optimisation purposes, we would also only fetch the locals and args of the other functions in the callstack after clicking by the user.

> But specifically for this PR. What still needs to be done so we can merge the fix for the index out of range?

Manual testing by me

**Comment by tolauwae** [comment]
Ah of course I was wrong:

> I see no real need to request locals from functions other than the current one. They can't update anyway, so we don't need to fetch them.

There are possibly functions on the callstack we haven't "seen" yet, after a breakpoint or running.

**Comment by carllocos** [comment]
@tolauwae so I just committed the fix and tested the fix manually. Everything seems to work now. However, for this I created a custom WAST file and did not test on the wast that you experienced the issue on. So maybe as a last review step, you can provide me with that file.

Also, I cannot change the reviewer to become you so I propose that if the fix works on your WAST file I then approve the PR.

**Comment by tolauwae** [comment]
I actually experienced it with almost any file, also handwritten. But this one definitely had it:
[code.zip](https://github.com/TOPLLab/WARDuino-VSCode/files/11867009/code.zip)

**Comment by tolauwae** [comment]
I'll double check on my end.

**Review by carllocos — APPROVED** [review]

**Pull request merged**
