### PR TITLE
Version 0.3.0

### PR DESCRIPTION
**Pull request by tolauwae**

### CODE REVIEW

**Comment by carllocos** [comment]
@tolauwae I believe the problem of waiting infinitely  is an issue on the emulator and not on the plugin side. When I comment the line that puts the thread to sleep in the VM, the plugin had no iesue interacting with the emulator. If my suspicion is correct you should then also experience this waiting infinitely problem with the main branch of the plugin and the main of the VM: both branches that do not contain the code related to the virtual addresses en inspect. Unfortunately, I carnot verify this at the moment as I'm out of office. 

The problem with the m5stickc-dimmer may be another issue. I'll look into it once I'm back.

**Comment by tolauwae** [comment]
I do not experience this with the main of both components.

**Comment by tolauwae** [comment]
Just realised this is issue TOPLLab/WARDuino#162, which I already fixed on staging. I will rebase feat/inspect in the VM repo, and this issue should disappear in de plugin.

**Comment by tolauwae** [comment]
I failed to rebase. There are a lot of merge conflicts between the virtual addresses and the inspect branch, which suprised me somewhat. @carllocos can you rebase `feat/inspect` to `staging` in the plugin. I think this is safest, I might well break something by merging incorrectly.

**Comment by carllocos** [comment]
@tolauwae sure I will handle the rebase

**Comment by carllocos** [comment]
@tolauwae I did the rebase of `feat/inspect` branch and also fixed the bugs that caused the unit tests to fail on OSX

@chscholl do you still experience the freeze problem at line nr 45? Because I tested on Ubuntu and OSX with `feat\inspect` as VM branch and I do not experiene that problem. So I'm just puzzled on how to solve that problem.

**Comment by tolauwae** [comment]
@carllocos no matter what I do in the settings of the plugin, it doesn't flash anymore.

**Comment by carllocos** [comment]
@tolauwae I will look into it

**Comment by tolauwae** [comment]
@carllocos I have managed to use the "pull session" command to test EDWARD. But only after trying multiple times.
Retrying now it never does anything.

**Comment by tolauwae** [comment]
I found the issue. Non related to this PR.

**Review by carllocos — APPROVED** [review]
Code looks fine. There is still need for some refactoring especially on my contribution but that would be lost time since we will eventually opt for the library.

@tolauwae I just notice however that WAB submodule is git tracked is that intentional? shouldn't we add it to gitignore?

**Pull request merged**
